version: "3.8"

services:
  backend:
    build: C:\Users\yosrm\IdeaProjects\competence-ms\backend\competence
    ports:
      - "8080:8080"

  frontend:
    build:
      context: C:\Users\yosrm\IdeaProjects\competence-ms\front
    ports:
      - "4200:4200"
